#!/bin/bash

if [ ! -d target ] || [ ! -f dive-classpath.txt ]
then
	mvn clean package
	mvn dependency:build-classpath -Dmdep.outputFile=dive-classpath.txt
fi

DIVE_CLASSPATH=target/classes:`cat dive-classpath.txt`

nohup java \
    -Djava.endorsed.dirs=target/endorsed \
    -Djava.net.preferIPv4Stack=true \
    -Xmx1024m \
    -cp $DIVE_CLASSPATH \
    de.farberg.dive.Main \
    --database database \
    --logLevel DEBUG \
    --port 8080 \
    2>&1 >> /dev/null &
    
echo $! >> dive.pid
